import type { PrismaClient } from '@prisma/client';

const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December',
];

/**
 * Mirror a freshly-imported non-compliance payroll run into a matching
 * compliance run for the same period, so it appears in the Compliance view
 * automatically. The compliance run is a copy of the same PayrollItems
 * (PT/TDS forced to 0); the compliance salary sheet derives the statutory
 * register columns from these fields.
 *
 * Idempotent per period: an existing compliance run for the month/year is
 * reused and its items replaced, so re-importing never accumulates duplicates.
 */
export async function syncComplianceRunFromNonCompliance(
  db: PrismaClient,
  sourcePayrollRunId: number,
  month: number,
  year: number,
): Promise<void> {
  const sourceItems = await db.payrollItem.findMany({
    where: { payrollRunId: sourcePayrollRunId },
  });
  if (sourceItems.length === 0) return;

  let complianceRun = await db.payrollRun.findFirst({
    where: { month, year, payrollType: 'compliance' },
    orderBy: { createdAt: 'desc' },
  });

  if (complianceRun) {
    // Replace previously mirrored items so counts stay correct
    await db.payrollItem.deleteMany({ where: { payrollRunId: complianceRun.id } });
  } else {
    complianceRun = await db.payrollRun.create({
      data: {
        name: `Compliance Payroll - ${MONTH_NAMES[month - 1]} ${year} (Auto)`,
        month,
        year,
        status: 'draft',
        payrollType: 'compliance',
        totalEmployees: 0,
        totalGross: 0,
        totalNet: 0,
        updatedAt: new Date(),
      },
    });
  }

  const runId = complianceRun.id;
  await db.payrollItem.createMany({
    data: sourceItems.map((it) => ({
      payrollRunId: runId,
      employeeId: it.employeeId,
      workingDays: it.workingDays,
      presentDays: it.presentDays,
      paidLeaveDays: it.paidLeaveDays,
      lopDays: it.lopDays,
      otHours: it.otHours,
      basicSalary: it.basicSalary,
      hra: it.hra,
      conveyanceAllowance: it.conveyanceAllowance,
      medicalAllowance: it.medicalAllowance,
      specialAllowance: it.specialAllowance,
      otAmount: it.otAmount,
      grossEarning: it.grossEarning,
      pfDeduction: it.pfDeduction,
      esiDeduction: it.esiDeduction,
      ptDeduction: 0,
      tdsDeduction: 0,
      lopDeduction: it.lopDeduction,
      otherDeductions: it.otherDeductions,
      totalDeduction: it.totalDeduction,
      netPay: it.netPay,
      status: 'pending',
      payslipGenerated: false,
      details: { autoGenerated: true, mirroredFrom: sourcePayrollRunId, format: 'compliance' },
    })),
  });

  const totalGross = sourceItems.reduce((s, i) => s + Number(i.grossEarning), 0);
  const totalNet = sourceItems.reduce((s, i) => s + Number(i.netPay), 0);

  await db.payrollRun.update({
    where: { id: runId },
    data: {
      totalEmployees: sourceItems.length,
      totalGross,
      totalNet,
      status: 'completed',
      processedAt: new Date(),
    },
  });
}
